### PR TITLE
PullRequest for Issue1708: change the dataType of Amptek to unsigned int 16

### PR DESCRIPTION
**Pull request by XuetaoLiu-S**

### CODE REVIEW

**Comment by dretrex** [comment]
Looks good.
Time Estimate: 1 minute

**Comment by dretrex** [comment]
@XuetaoLiu-CLS is there any more to this pull request?  If not, we may as well merge it in, right?

**Comment by XuetaoLiu-S** [comment]
@dretrex I will relook into this PR later

**Comment by XuetaoLiu-S** [comment]
This will only change the AMDS amptek server to use usigned 16 type.
For acquaman side, it will use double no matter what the AMDS type is.

Issue https://github.com/acquaman/acquaman/issues/1720 will request to have a helper function to convert all data holder type to double...

**Pull request merged**
