### PR TITLE
Pull Request for Issue135: Scaler Buffer Size Limited to One Minute

### PR DESCRIPTION
**Pull request by iainworkman**
Increased it to 20 minutes.

### CODE REVIEW

**Comment by iainworkman** [comment]
Hey @XuetaoLiu-CLS, would you mind looking over this one for me?

Thanks.

**Comment by XuetaoLiu-S** [comment]
Looks good. 
@iainworkman are you going to change the dwellTime of Amptek from int to double or you want me to do that?

**Comment by iainworkman** [comment]
Done in #134

**Comment by dretrex** [comment]
@iainworkman, what do you mean that it's been done in #134?  This change doesn't appear in that pull request from what I can tell.

**Comment by XuetaoLiu-S** [comment]
@iainworkman got it. Thanks.
@dretrex @iainworkman means the integer dwellTime issue I asked for.

**Comment by iainworkman** [comment]
@dretrex Sorry, that was in answer to Sheldon's question. The alteration to change the amptek dwell time from int to double was already done in #134.

**Comment by dretrex** [comment]
Gotcha.

**Comment by dretrex** [comment]
Time Estimate: 1 minute

**Pull request merged**
